from turtle import Turtle, Screen

f = open("./ScrivereComandiTurtle",'w')
tartaruga = Turtle()
f.write("Turle()")
sfondo = Screen()
f.write("Screen()")

tartaruga.speed(0)
f.write("tartaruga.speed()")
tartaruga.goto(30,20)
f.write("tartaruga.goto()")
sfondo.colormode(255)
sfondo.bgcolor((10, 10, 10))
tartaruga.color(150,250,255)

def Ramo(tartaruga,grado):
    #Linea centrale sotto il Ramo piccolo Sinistro
    tartaruga.forward(30)
    f.write("tartaruga.forward()")

    #Ramo piccolo Sinistro
    tartaruga.left(grado)
    f.write("tartaruga.left()")
    tartaruga.forward(25)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(15)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(5)
    f.write("tartaruga.forward()")
    tartaruga.left(grado*3)
    f.write("tartaruga.left()")
    #Finisce cambiando la direzione ma non creando il ramo tra il ramo Piccolo Sinistro e
    #Ramo grande 

    #Ramo grande
        #Linea centrale tra Ramo piccolo Sinistro e Ramo Grande.
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    
    tartaruga.left(grado)
    f.write("tartaruga.left()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(10)
    f.write("tartaruga.forward()")
    tartaruga.left(grado*3)
    f.write("tartaruga.left()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.left(grado*3)
    f.write("tartaruga.left()")
    tartaruga.forward(10)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.left(grado)
    f.write("tartaruga.left()")
    #Linea Ramo Grande e Ramo Piccolo Destro.
    tartaruga.forward(20)
    f.write("tartaruga.forward()")

    #Ramo piccolo sinistro
    tartaruga.left(grado*3)
    f.write("tartaruga.left()")
    tartaruga.forward(5)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(15)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(25)
    f.write("tartaruga.forward()")
    tartaruga.left(grado)
    f.write("tartaruga.left()")
    
    #Linea centrale dopo Ramo piccolo Destro.
    tartaruga.forward(30)
    f.write("tartaruga.forward()")

for _ in range(6):
    Ramo(tartaruga,45)
    tartaruga.left(120)
    f.write("tartaruga.left()")
f.close()
sfondo.exitonclick()
