from turtle import Turtle, Screen

f = open("./ScrivereComandiTurtle",'w')
tartaruga = Turtle()
f.write("Turle()")
sfondo = Screen()
f.write("Screen()")

tartaruga.speed(0)
f.write("tartaruga.speed()")
tartaruga.goto(50,20)
f.write("tartaruga.goto()")
sfondo.colormode(255)
sfondo.bgcolor((10, 10, 10))
tartaruga.color(150,250,255)

def Ramo(tartaruga,grado):
    tartaruga.forward(80)
    f.write("tartaruga.forward()")
    tartaruga.left(grado)
    f.write("tartaruga.left()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(10)
    f.write("tartaruga.forward()")
    tartaruga.left(grado*3)
    f.write("tartaruga.left()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.left(grado*3)
    f.write("tartaruga.left()")
    tartaruga.forward(10)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado*2)
    f.write("tartaruga.right()")
    tartaruga.forward(20)
    f.write("tartaruga.forward()")
    tartaruga.right(grado)
    f.write("tartaruga.right()")
    tartaruga.forward(30)
    f.write("tartaruga.forward()")
    tartaruga.left(grado)
    f.write("tartaruga.left()")
    tartaruga.forward(80)
    f.write("tartaruga.forward()")

for i in range(9):
    Ramo(tartaruga,45)
    tartaruga.left(140)
    f.write("tartaruga.left()")
f.close()
sfondo.exitonclick()

