nome = input("Dimmi il tuo nome: ")
#anni = int(input("Dimmi la tua età: "))
print(f"Il tuo nome inizia per {nome[0]}")
print(f"Il tuo nome finisce per {nome[-1]}")
print(f"La penultima lettera del tuo nome è {nome[-2]}")